### PR TITLE
Added new frontend developer job listing ( Peter Griffin )

### PR DESCRIPTION
**Pull request by Dheeerazzz**
I have inserted a new webpage (99th one) to the original webpage and named it "Peter Griffin".

### CODE REVIEW

**Review by KyleShook — APPROVED** [review]
Well done! Thanks for contributing! @Dheeerazzz 

Feel free to merge whenever you'd like.

**Comment by Dheeerazzz** [comment]
> Well done! Thanks for contributing! @Dheeerazzz
> 
> Feel free to merge whenever you'd like.

>Hello @KyleShook . Thanks for appreciating my work. I don't know how to merge the project. Can you guide me through it.

**Review by KyleShook — APPROVED** [review]
@Dheeerazzz If you scroll down some, you should be able to click "Squash and Merge" and then "Confirm". If you do not have this option, I can merge it for you.

image

**Comment by Dheeerazzz** [comment]
> @Dheeerazzz If you scroll down some, you should be able to click "Squash and Merge" and then "Confirm". If you do not have this option, I can merge it for you.
> 
> image

> Thanks for the quick response @KyleShook . I can't find the option you mentioned . Can you do it for me ?

**Pull request merged**
